# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(core)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/cache"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(cache)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/drivers/bbolt"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(drivers/bbolt)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/drivers/cassandra"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(drivers/cassandra)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/drivers/hashmap"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(drivers/hashmap)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/drivers/mock"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(drivers/mock)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/drivers/nats"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(drivers/nats)"
      include: "scope"
  
  - package-ecosystem: "gomod"
    directory: "/drivers/redis"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(drivers/redis)"
      include: "scope"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
