name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          command: manifest
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-labeling: true
          skip-github-pull-request: true
